### ISSUE TITLE
Any trick for the results reported in the paper

### ISSUE THREAD

**Issue by csyanbin** [yoonholee/MT-net#1]
Hi, yoohholee,
      MT-net is a fantastic idea. 
      I ran this code but only got 50.04% for miniImagenet 1-shot classification.

      Do you have any suggestions or recommendations to reproduce the results in the paper?
      Such as data preprocessing, validation, tensorflow and python version or maybe other tricks?

       Thanks so much!

**Comment by yoonholee** [comment]
Thank you for your interest in our work:)

The data preprocessing/validation code shouldn't be any different from what I used to get the results for the paper.
Unfortunately, I'm not exactly sure which version of tensorflow and python I used.
In my experiments, the hyperparameters that the method is most sensitive to was update_lr. I'd suggest trying to alter update_lr a bit if you want to tweak for performance.
